Document: sparc
Title: Debian sparc Manual
Author: <insert document author here>
Abstract: This manual describes what sparc is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sparc/sparc.sgml.gz

Format: postscript
Files: /usr/share/doc/sparc/sparc.ps.gz

Format: text
Files: /usr/share/doc/sparc/sparc.text.gz

Format: HTML
Index: /usr/share/doc/sparc/html/index.html
Files: /usr/share/doc/sparc/html/*.html
